name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "YGMJIFE"
